Add several Functions and Supports Win 11 (#13)
* Update lighthouse-v2-manager.py

* Update README.md

* Update README.md

* Update README.md

* Update lighthouse-v2-manager.py

import bleak, fixes win11 not working

* small bugfix
bleak.exc.BleakError: Device with address D7:4C:07:1D:8E:C1 was not found.
[20304] Failed to execute script lighthouse-v2-manager

* remove deprecated functions

https://bleak.readthedocs.io/en/latest/api/client.html#deprecated

* remove deprecated functions

https://bleak.readthedocs.io/en/latest/api/client.html#deprecated

* use var instead of string

* fix indent and improve code

Don't loop again if it is Valve BS

* Print list of BS end of discover mode

* Unified naming to LH

* formatting using black

--line-length=120

* add retrying function

---------

Co-authored-by: Skyro468 <32147348+Skyro468@users.noreply.github.com>
Co-authored-by: Muhlawor <17768574+Muhlawor@users.noreply.github.com>
Co-authored-by: Pixie Raver <PixieRaveGirl@gmail.com>